### ISSUE TITLE
Not working with newer jquery

### ISSUE THREAD

**Issue by Bero83** [baivong/watermark#15]
Doesn't work with jquery 1.9.1

.watermark is not a function

**Comment by lelinhtinh** [comment]
It's still working with jQuery 1.9.1
**Demo**: [https://jsbin.com/qiqibuvino/1/](https://jsbin.com/qiqibuvino/1/edit?html,output)

**Comment by Bero83** [comment]
I took a look at the source of jquery.watermark.js  and on the bottem of th file, there was this function:

//    $.fn[pluginName] = function (options) {

        return this.each(function () {

           if (!$.data(this, 'plugin_' + pluginName)) {

               $.data(this, 'plugin_' + pluginName, new Plugin(this, options));

            }

//        });

    };


I don’t know how the ‘//’ came there, but when I removed it, it worked..
Thank you for your time. Will put it at the github later this day.



p.s. demo gives 504 bad gateway time-out

Van: Lê Thành [mailto:notifications@github.com] 
Verzonden: woensdag 11 oktober 2017 3:49
Aan: baivong/watermark <watermark@noreply.github.com>
CC: Bero83 <jp.belmer@belsshoeservice.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [baivong/watermark] Not working with newer jquery (#15)

 

It's still working with jQuery 1.9.1
Demo: https://jsbin.com/qiqibuvino/1/ <https://jsbin.com/qiqibuvino/1/edit?html,output>
